[tool.poetry]
name = "shopify-theme-sync"
version = "0.1.0"
description = ""
authors = ["Josh Kremer <joshkremer@gmail.com>"]
readme = "README.md"
packages = [{include = "shopify_theme_sync"}]

[tool.poetry.dependencies]
python = "^3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
